#!/usr/bin/env bash
# This script installs and configures HAproxy on a new Ubuntu machine

# Update the package list
sudo apt-get update

# Install HAproxy
sudo apt-get install -y haproxy

# Enable HAproxy to be started by the init script
sudo systemctl enable haproxy

# Define the configuration for HAproxy
cat << EOF | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back

backend http_back
   balance roundrobin
   server web-01 54.164.162.167:80 check
   server web-02 52.205.90.128:80 check
EOF

# Restart HAproxy to apply the changes
sudo systemctl restart haproxy

echo "HAproxy has been installed and configured successfully."
