#!/usr/bin/env bash
# Displays 'To infinity and beyond' indefinitely with a 2-second pause
# and prints 'I am invincible!!!' when receiving a SIGTERM signal

trap "echo 'I am invincible!!!'; exit" SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
