#!/usr/bin/env bash
# This script displays numbers from 1 to 20 except for 4th, 9th, and 17th

counter=1
while [ $counter -le 20 ]
do
  case $counter in
    4)
      echo "4"
      echo "bad luck from China"
      ;;
    9)
      echo "9"
      echo "bad luck from Japan"
      ;;
    17)
      echo "17"
      echo "bad luck from Italy"
      ;;
    *)
      echo $counter
      ;;
  esac
  ((counter++))
done
